version: '3.6'

services:
  BCFD:
    restart: always
    image: simonloudev/lscofd_web
    container_name: 'LSCoFD'
    volumes:
      - lscofd_storage:/usr/share/nginx/lscofd/storage
    environment:
      - VIRTUAL_HOST=lscofd.simon-lou.com
      - VIRTUAL_PORT=80
    expose:
      - 80

volumes:
  lscofd_storage:

networks:
  default:
    external:
      name: nginx-proxy
